/* I had to put the myext.dll in the same directory as the
existing Oracle dll with a complete pathe specificaton separately by a semi-colon


# listener.ora Network Configuration File: C:\Oracle18c\NETWORK\ADMIN\listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = CLRExtProc)
      (ORACLE_HOME = C:\Oracle18c)
      (PROGRAM = extproc)
      (ENVS = "EXTPROC_DLLS=ONLY:C:\Oracle18c\bin\oraclr18.dll;C:\Oracle18c\bin\myext.dll")
    )
  )

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = Oracle)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )





*/

set serveroutput on

CREATE OR REPLACE LIBRARY my_c_lib
AS 'C:\Oracle18c\bin\myext.dll';
/


CREATE OR REPLACE FUNCTION add_two_numbers_plsql(a IN BINARY_INTEGER,
                                                 b IN BINARY_INTEGER)
RETURN BINARY_INTEGER
AS
    EXTERNAL
    LIBRARY my_c_lib
    NAME "add_two_numbers"
    LANGUAGE C
    PARAMETERS (a INT, b INT, RETURN INT);
/


DECLARE
    result NUMBER;
BEGIN
    result := add_two_numbers_plsql(10, 20);
    DBMS_OUTPUT.put_line('Result = ' || result);
END;
/


